app:
  env: "development"
  port: ":8080"
  debug: true

log:
  level: "debug"
  format: "json"

database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: test
  dbname: postgres

redis:
  dsn: "redis:6379"

jwt:
  access_secret: "918bb09f-a109-4071-9883-b75899b1918b"
  refresh_secret: "7b065650-3126-4e8d-ae7f-36a184c56baf"
