app:
  env: "development"
  port: ":8080"
  debug: true

log:
  level: "debug"
  format: "json"

database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: test
  dbname: postgres

redis:
  dsn: "redis:6379"
